<?php
/**
 * Platform → Hotels: list, create / edit, suspend / activate, enter a hotel (switch the
 * session's hotel context), hotel details with users and invoices.
 */
declare(strict_types=1);
require __DIR__ . '/../core/bootstrap.php';
require_once __DIR__ . '/partials/platform.php';
require_once __DIR__ . '/partials/panel_ui.php';

$user = Auth::require();
Csrf::check();

// "Back to platform" from the hotel-context banner (any platform user).
if (is_post() && req_str('op', $_POST, 20) === 'leave') {
    Auth::leaveHotel();
    redirect(admin_url(Auth::homePage())); // 2.6: back to the user's own console
}
require_can('platform.manage');

if (is_post()) {
    $op = req_str('op', $_POST, 20);
    $id = req_int('id', $_POST);
    $hotel = $id ? Hotels::find($id) : null;
    if ($id && !$hotel) {
        flash('warning', __('Customer not found.'));
        redirect(admin_url('platform_hotels.php'));
    }
    try {
        switch ($op) {
            case 'save':
                $back = admin_url('platform_hotels.php', $hotel ? ['action' => 'edit', 'id' => $id] : ['action' => 'new']);
                $id = platform_save_hotel($hotel, null, $back);
                redirect(admin_url('platform_customer.php', ['id' => $id]));

            case 'status':
                $status = req_str('status', $_POST, 20);
                Hotels::setStatus($id, $status, 'manual');
                ActivityLog::add('hotel_status', 'hotel', $id, $hotel['name'] . ' → ' . $status);
                flash('success', __('Customer ":n" is now :s.', ['n' => $hotel['name'], 's' => __(ucfirst($status))]));
                redirect(admin_url('platform_customer.php', ['id' => $id]));

            case 'enter':
                if (Auth::enterHotel($id)) {
                    redirect(admin_url('index.php'));
                }
                flash('danger', __('You cannot open this customer.'));
                break;

            case 'regen_key':
                $key = Hotels::newRegistrationKey();
                Settings::setFor($id, 'registration_key', $key);
                ActivityLog::add('registration_key_regen', 'hotel', $id, 'Registration key regenerated by platform');
                flash('success', __('New registration key created. TVs that are already set up keep working; new TVs need the new key.'));
                redirect(admin_url('platform_customer.php', ['id' => $id]));

            case 'set_chain':
                // Hotel chains (#20): assign / remove the hotel's chain (only while the feature is on).
                Chains::requireEnabled();
                $chainId = req_int('chain_id', $_POST);
                if ($hotel['chain_id'] && (int) $hotel['chain_id'] !== $chainId) {
                    Chains::assignHotel((int) $hotel['chain_id'], $id, false);
                }
                if ($chainId) {
                    Chains::assignHotel($chainId, $id, true);
                }
                ActivityLog::add('chain_hotel_set', 'hotel', $id, $hotel['name'] . ' → chain #' . $chainId);
                flash('success', __('Saved.'));
                redirect(admin_url('platform_customer.php', ['id' => $id]));

            case 'add_admin':
                [$admin, $errors] = Hotels::validateAdmin($_POST, true);
                if ($errors) {
                    flash_errors($errors);
                } else {
                    $uid = Hotels::createHotelUser($id, $admin, 'super_admin');
                    ActivityLog::add('user_create', 'user', $uid, $admin['username'] . ' (super_admin of customer #' . $id . ')');
                    flash('success', __('Super admin :u created.', ['u' => $admin['username']]));
                }
                redirect(admin_url('platform_customer.php', ['id' => $id]));
        }
    } catch (InvalidArgumentException | RuntimeException $e) {
        flash('danger', $e->getMessage());
    }
    redirect(admin_url('platform_hotels.php'));
}

$action = req_str('action', $_GET, 20);
$activeNav = 'platform_hotels';

// ---------------------------------------------------------------- create / edit
if ($action === 'new' || $action === 'edit') {
    $h = ['id' => 0, 'status' => 'active'];
    if ($action === 'edit') {
        $h = Hotels::find(req_int('id', $_GET));
        if (!$h) {
            flash('warning', __('Customer not found.'));
            redirect(admin_url('platform_hotels.php'));
        }
    }
    $pageTitle = $h['id'] ? __('Edit customer') : __('New customer');
    require __DIR__ . '/partials/header.php';
    ?>
    <div class="page-head">
      <h1><?= e($pageTitle) ?><?= $h['id'] ? ' — ' . e($h['name']) : '' ?></h1>
      <a class="btn btn-light border" href="<?= e(admin_url('platform_hotels.php', $h['id'] ? ['action' => 'view', 'id' => $h['id']] : [])) ?>"><i class="bi bi-arrow-left"></i> <?= e(__('Back')) ?></a>
    </div>
    <form method="post" enctype="multipart/form-data">
      <?= Csrf::field() ?><input type="hidden" name="op" value="save"><input type="hidden" name="id" value="<?= (int) $h['id'] ?>">
      <?= hotel_form_fields($h, false, !$h['id']) ?>
      <div class="sticky-actions mt-3"><button class="btn btn-primary btn-lg"><i class="bi bi-check-lg"></i> <?= e(__('Save customer')) ?></button></div>
    </form>
    <?php
    require __DIR__ . '/partials/footer.php';
    exit;
}

// ---------------------------------------------------------------- details (2.6: the Customer 360 page)
if ($action === 'view') {
    redirect(admin_url('platform_customer.php', ['id' => req_int('id', $_GET)]));
}
// ---------------------------------------------------------------- list
$q = req_str('q', $_GET, 60);
$fStatus = req_str('status', $_GET, 20);
$hotels = Hotels::all(null, $q, $fStatus);
$psUsers = PlatformScreens::usersPerCustomer(null); // 2.5 platform screens: "Users" column
$totals = ['hotels' => count($hotels), 'tvs' => array_sum(array_column($hotels, 'tv_count')), 'online' => array_sum(array_column($hotels, 'tv_online')),
    'suspended' => count(array_filter($hotels, fn ($h) => $h['status'] !== 'active'))];
$pageTitle = __('Customers');
require __DIR__ . '/partials/header.php';
?>
<div class="page-head">
  <div><h1><?= e(__('Customers')) ?></h1><p class="lead-sm"><?= e(__('Every customer on this platform, with its plan, TVs and status.')) ?></p></div>
  <a class="btn btn-primary" href="<?= e(admin_url('platform_hotels.php', ['action' => 'new'])) ?>"><i class="bi bi-plus-lg"></i> <?= e(__('New customer')) ?></a>
</div>
<div class="row g-3 mb-3">
  <?php foreach ([['bi-buildings', 'bg-soft-primary', __('Customers'), $totals['hotels']], ['bi-tv', 'bg-soft-info', __('TVs'), $totals['tvs']],
      ['bi-wifi', 'bg-soft-success', __('TVs online'), $totals['online']], ['bi-pause-circle', 'bg-soft-danger', __('Suspended / expired'), $totals['suspended']]] as [$icon, $cls, $label, $val]): ?>
    <div class="col-6 col-lg-3"><div class="card h-100"><div class="stat-card"><div class="stat-icon <?= e($cls) ?>"><i class="bi <?= e($icon) ?>"></i></div><div><div class="stat-value"><?= (int) $val ?></div><div class="stat-label"><?= e($label) ?></div></div></div></div></div>
  <?php endforeach; ?>
</div>
<?php require __DIR__ . '/partials/platform_screens_dashboard.php'; // 2.5: screens counters, top / offline customers ?>
<form class="d-flex flex-wrap gap-2 mb-3" method="get">
  <input class="form-control" style="max-width:18rem" name="q" value="<?= e($q) ?>" placeholder="<?= e(__('Search customer, city, email…')) ?>">
  <select class="form-select" style="max-width:12rem" name="status">
    <option value=""><?= e(__('All statuses')) ?></option>
    <?php foreach (['active' => __('Active'), 'suspended' => __('Suspended'), 'expired' => __('Expired')] as $s => $l): ?><option value="<?= e($s) ?>"<?= $fStatus === $s ? ' selected' : '' ?>><?= e($l) ?></option><?php endforeach; ?>
  </select>
  <button class="btn btn-outline-primary"><i class="bi bi-search"></i> <?= e(__('Filter')) ?></button>
</form>
<div class="card">
<?php if (!$hotels): ?>
  <div class="hc-empty"><i class="bi bi-buildings"></i><p class="mb-1"><strong><?= e(__('No customers found')) ?></strong></p></div>
<?php else: ?>
  <div class="table-responsive">
    <table class="table table-hc table-hover">
      <thead><tr><th><?= e(__('Customer')) ?></th><th class="d-none d-md-table-cell"><?= e(__('Plan')) ?></th><th><?= e(__('TVs')) ?></th><th class="d-none d-md-table-cell"><?= e(__('Screens (online/total)')) ?></th><th class="d-none d-md-table-cell"><?= e(__('Users')) ?></th><th class="d-none d-lg-table-cell"><?= e(__('Reseller')) ?></th><th><?= e(__('Status')) ?></th><th class="text-end"><?= e(__('Actions')) ?></th></tr></thead>
      <tbody>
      <?php foreach ($hotels as $h): $max = $h['max_tvs'] !== null ? (int) $h['max_tvs'] : ($h['plan_max_tvs'] !== null ? (int) $h['plan_max_tvs'] : null); ?>
        <tr>
          <td><a class="fw-semibold text-decoration-none" href="<?= e(admin_url('platform_customer.php', ['id' => $h['id']])) ?>"><?= e($h['name']) ?></a>
            <div class="small text-muted"><?= e(trim(($h['city'] ?? '') . ' #' . $h['id'])) ?><?= (int) $h['unpaid_invoices'] ? ' · <span class="text-danger">' . e(__(':n unpaid', ['n' => $h['unpaid_invoices']])) . '</span>' : '' ?></div></td>
          <td class="d-none d-md-table-cell small"><?= e($h['plan_name'] ?? '—') ?></td>
          <td class="text-nowrap"><?= e(tv_usage_label((int) $h['tv_count'], $max)) ?> <span class="small text-success">(<?= (int) $h['tv_online'] ?> <?= e(__('online')) ?>)</span></td>
          <td class="d-none d-md-table-cell text-nowrap"><a class="text-decoration-none" href="<?= e(admin_url('platform_customer.php', ['id' => $h['id'], 'tab' => 'screens'])) ?>"><span class="text-success"><?= (int) $h['tv_online'] ?></span> / <?= (int) $h['tv_count'] ?></a></td>
          <td class="d-none d-md-table-cell"><a class="text-decoration-none" href="<?= e(admin_url('platform_customer.php', ['id' => $h['id'], 'tab' => 'users'])) ?>"><?= (int) ($psUsers[(int) $h['id']] ?? 0) ?></a></td>
          <td class="d-none d-lg-table-cell small"><?= e($h['reseller_name'] ?? '—') ?></td>
          <td><div class="d-flex align-items-center gap-2"><span data-status-badge="<?= (int) $h['id'] ?>"><?= Hotels::statusBadge($h['status'] === 'active' && $h['expires_at'] && strtotime((string) $h['expires_at']) < time() ? 'expired' : $h['status']) ?></span>
            <?= panel_switch('customer_status', (int) $h['id'], $h['status'] === 'active', '', __('Suspend this customer? Its TVs show the "service paused" screen and its admin panel becomes read-only.'), '', [], $h['status'] === 'expired') ?></div></td>
          <td class="text-end text-nowrap">
            <a class="btn btn-sm btn-primary" href="<?= e(admin_url('platform_customer.php', ['id' => $h['id']])) ?>" title="<?= e(__('Customer 360')) ?>"><i class="bi bi-card-list"></i> <span class="d-none d-sm-inline"><?= e(__('Manage')) ?></span></a>
            <?= panel_open_workspace((int) $h['id'], 'platform_hotels.php', 'sm') ?>
            <a class="btn btn-sm btn-light border" href="<?= e(admin_url('platform_hotels.php', ['action' => 'edit', 'id' => $h['id']])) ?>" title="<?= e(__('Edit')) ?>"><i class="bi bi-pencil"></i></a>
          </td>
        </tr>
      <?php endforeach; ?>
      </tbody>
    </table>
  </div>
<?php endif; ?>
</div>
<?php require __DIR__ . '/partials/footer.php'; ?>
