<?php
/**
 * Platform → Hotels: list, create / edit, suspend / activate, enter a hotel (switch the
 * session's hotel context), hotel details with users and invoices.
 */
declare(strict_types=1);
require __DIR__ . '/../core/bootstrap.php';
require_once __DIR__ . '/partials/platform.php';

$user = Auth::require();
Csrf::check();

// "Back to platform" from the hotel-context banner (any platform user).
if (is_post() && req_str('op', $_POST, 20) === 'leave') {
    Auth::leaveHotel();
    redirect(admin_url(Auth::homePage())); // 2.6: back to the user's own console
}
require_can('platform.manage');

if (is_post()) {
    $op = req_str('op', $_POST, 20);
    $id = req_int('id', $_POST);
    $hotel = $id ? Hotels::find($id) : null;
    if ($id && !$hotel) {
        flash('warning', __('Customer not found.'));
        redirect(admin_url('platform_hotels.php'));
    }
    try {
        switch ($op) {
            case 'save':
                $back = admin_url('platform_hotels.php', $hotel ? ['action' => 'edit', 'id' => $id] : ['action' => 'new']);
                $id = platform_save_hotel($hotel, null, $back);
                redirect(admin_url('platform_hotels.php', ['action' => 'view', 'id' => $id]));

            case 'status':
                $status = req_str('status', $_POST, 20);
                Hotels::setStatus($id, $status, 'manual');
                ActivityLog::add('hotel_status', 'hotel', $id, $hotel['name'] . ' → ' . $status);
                flash('success', __('Customer ":n" is now :s.', ['n' => $hotel['name'], 's' => __(ucfirst($status))]));
                redirect(admin_url('platform_hotels.php', ['action' => 'view', 'id' => $id]));

            case 'enter':
                if (Auth::enterHotel($id)) {
                    redirect(admin_url('index.php'));
                }
                flash('danger', __('You cannot open this customer.'));
                break;

            case 'regen_key':
                $key = Hotels::newRegistrationKey();
                Settings::setFor($id, 'registration_key', $key);
                ActivityLog::add('registration_key_regen', 'hotel', $id, 'Registration key regenerated by platform');
                flash('success', __('New registration key created. TVs that are already set up keep working; new TVs need the new key.'));
                redirect(admin_url('platform_hotels.php', ['action' => 'view', 'id' => $id]));

            case 'set_chain':
                // Hotel chains (#20): assign / remove the hotel's chain (only while the feature is on).
                Chains::requireEnabled();
                $chainId = req_int('chain_id', $_POST);
                if ($hotel['chain_id'] && (int) $hotel['chain_id'] !== $chainId) {
                    Chains::assignHotel((int) $hotel['chain_id'], $id, false);
                }
                if ($chainId) {
                    Chains::assignHotel($chainId, $id, true);
                }
                ActivityLog::add('chain_hotel_set', 'hotel', $id, $hotel['name'] . ' → chain #' . $chainId);
                flash('success', __('Saved.'));
                redirect(admin_url('platform_hotels.php', ['action' => 'view', 'id' => $id]));

            case 'add_admin':
                [$admin, $errors] = Hotels::validateAdmin($_POST, true);
                if ($errors) {
                    flash_errors($errors);
                } else {
                    $uid = Hotels::createHotelUser($id, $admin, 'super_admin');
                    ActivityLog::add('user_create', 'user', $uid, $admin['username'] . ' (super_admin of customer #' . $id . ')');
                    flash('success', __('Super admin :u created.', ['u' => $admin['username']]));
                }
                redirect(admin_url('platform_hotels.php', ['action' => 'view', 'id' => $id]));
        }
    } catch (InvalidArgumentException | RuntimeException $e) {
        flash('danger', $e->getMessage());
    }
    redirect(admin_url('platform_hotels.php'));
}

$action = req_str('action', $_GET, 20);
$activeNav = 'platform_hotels';

// ---------------------------------------------------------------- create / edit
if ($action === 'new' || $action === 'edit') {
    $h = ['id' => 0, 'status' => 'active'];
    if ($action === 'edit') {
        $h = Hotels::find(req_int('id', $_GET));
        if (!$h) {
            flash('warning', __('Customer not found.'));
            redirect(admin_url('platform_hotels.php'));
        }
    }
    $pageTitle = $h['id'] ? __('Edit customer') : __('New customer');
    require __DIR__ . '/partials/header.php';
    ?>
    <div class="page-head">
      <h1><?= e($pageTitle) ?><?= $h['id'] ? ' — ' . e($h['name']) : '' ?></h1>
      <a class="btn btn-light border" href="<?= e(admin_url('platform_hotels.php', $h['id'] ? ['action' => 'view', 'id' => $h['id']] : [])) ?>"><i class="bi bi-arrow-left"></i> <?= e(__('Back')) ?></a>
    </div>
    <form method="post" enctype="multipart/form-data">
      <?= Csrf::field() ?><input type="hidden" name="op" value="save"><input type="hidden" name="id" value="<?= (int) $h['id'] ?>">
      <?= hotel_form_fields($h, false, !$h['id']) ?>
      <div class="sticky-actions mt-3"><button class="btn btn-primary btn-lg"><i class="bi bi-check-lg"></i> <?= e(__('Save customer')) ?></button></div>
    </form>
    <?php
    require __DIR__ . '/partials/footer.php';
    exit;
}

// ---------------------------------------------------------------- details
if ($action === 'view') {
    $h = Hotels::find(req_int('id', $_GET));
    if (!$h) {
        flash('warning', __('Customer not found.'));
        redirect(admin_url('platform_hotels.php'));
    }
    $hid = (int) $h['id'];
    $users = DB::all('SELECT id, username, full_name, email, role, is_active, last_login_at FROM users WHERE hotel_id = :h ORDER BY FIELD(role, \'platform_admin\', \'super_admin\', \'manager\', \'staff\', \'reception\'), username', ['h' => $hid]);
    $invoices = DB::all('SELECT * FROM invoices WHERE hotel_id = :h ORDER BY id DESC LIMIT 12', ['h' => $hid]);
    $tvs = Tenant::tvCount($hid);
    $online = (int) DB::value("SELECT COUNT(*) FROM devices WHERE hotel_id = :h AND is_revoked = 0 AND room_id IS NOT NULL AND status = 'online'", ['h' => $hid]);
    $rooms = (int) DB::value('SELECT COUNT(*) FROM rooms WHERE hotel_id = :h', ['h' => $hid]);
    $max = Tenant::maxTvs($hid);
    $state = Tenant::state($hid);
    $regKey = (string) Settings::getFor($hid, 'registration_key', '');
    $pageTitle = $h['name'];
    require __DIR__ . '/partials/header.php';
    ?>
    <div class="page-head">
      <div>
        <h1><i class="bi bi-building"></i> <?= e($h['name']) ?> <?= Hotels::statusBadge($state) ?></h1>
        <p class="lead-sm"><?= e(dot_trim(($h['city'] ?? '') . ' · ' . ($h['plan_name'] ?? __('No plan')) . ($h['reseller_name'] ? ' · ' . __('Reseller') . ': ' . $h['reseller_name'] : ''))) ?></p>
      </div>
      <div class="d-flex flex-wrap gap-2">
        <form method="post"><?= Csrf::field() ?><input type="hidden" name="op" value="enter"><input type="hidden" name="id" value="<?= $hid ?>">
          <button class="btn btn-primary"><i class="bi bi-box-arrow-in-right"></i> <?= e(__('Enter customer')) ?></button></form>
        <a class="btn btn-outline-primary" href="<?= e(admin_url('platform_hotels.php', ['action' => 'edit', 'id' => $hid])) ?>"><i class="bi bi-pencil"></i> <?= e(__('Edit')) ?></a>
        <a class="btn btn-outline-primary" href="<?= e(admin_url('platform_customer.php', ['id' => $hid])) ?>"><i class="bi bi-card-list"></i> <?= e(__('Customer details')) ?></a><?php /* 2.5 platform screens */ ?>
        <?php if ($h['status'] === 'active'): ?>
          <form method="post" data-confirm="<?= e(__('Suspend this customer? Its TVs show the "service paused" screen and its admin panel becomes read-only.')) ?>">
            <?= Csrf::field() ?><input type="hidden" name="op" value="status"><input type="hidden" name="status" value="suspended"><input type="hidden" name="id" value="<?= $hid ?>">
            <button class="btn btn-outline-danger"><i class="bi bi-pause-circle"></i> <?= e(__('Suspend')) ?></button></form>
        <?php else: ?>
          <form method="post"><?= Csrf::field() ?><input type="hidden" name="op" value="status"><input type="hidden" name="status" value="active"><input type="hidden" name="id" value="<?= $hid ?>">
            <button class="btn btn-success"><i class="bi bi-play-circle"></i> <?= e(__('Activate')) ?></button></form>
        <?php endif; ?>
        <a class="btn btn-light border" href="<?= e(admin_url('platform_hotels.php')) ?>"><i class="bi bi-arrow-left"></i> <?= e(__('Back')) ?></a>
      </div>
    </div>
    <div class="row g-3 mb-3">
      <?php foreach ([
          ['bi-tv', 'bg-soft-primary', __('TVs'), tv_usage_label($tvs, $max)],
          ['bi-wifi', 'bg-soft-success', __('TVs online'), (string) $online],
          ['bi-door-closed', 'bg-soft-secondary', __('Screens'), (string) $rooms],
          ['bi-calendar-check', 'bg-soft-info', __('Valid until'), $h['expires_at'] ? date('d M Y', (int) strtotime((string) $h['expires_at'])) : __('No expiry')],
      ] as [$icon, $cls, $label, $value]): ?>
        <div class="col-6 col-lg-3"><div class="card h-100"><div class="stat-card"><div class="stat-icon <?= e($cls) ?>"><i class="bi <?= e($icon) ?>"></i></div><div class="min-w-0"><div class="stat-value"><?= e($value) ?></div><div class="stat-label"><?= e($label) ?></div></div></div></div></div>
      <?php endforeach; ?>
    </div>
    <div class="row g-3">
      <div class="col-lg-6">
        <div class="card mb-3"><div class="card-header"><?= e(__('Details')) ?></div>
          <table class="table table-sm table-hc mb-0">
            <?php foreach ([
                __('Slug / login link') => admin_url('login.php', ['b' => $h['slug']]),
                __('Registration key') => $regKey,
                __('Contact person') => $h['contact_name'],
                __('Phone / WhatsApp') => $h['contact_phone'],
                __('Billing email') => $h['contact_email'],
                __('GSTIN') => $h['gstin'],
                __('Address') => trim(($h['address'] ?? '') . ' ' . ($h['city'] ?? '')),
                __('Price per TV / month') => $h['price_per_tv_month'] !== null ? money($h['price_per_tv_month']) : '—',
                __('Suspend reason') => $h['status'] !== 'active' ? (string) $h['suspend_reason'] : '',
                __('Created') => $h['created_at'],
            ] as $k => $val): if ((string) $val === '') continue; ?>
              <tr><th class="ps-3 text-muted fw-normal" style="width:40%"><?= e($k) ?></th><td class="text-break"><?= e($val) ?></td></tr>
            <?php endforeach; ?>
          </table>
          <div class="card-body pt-2">
            <form method="post" class="d-inline" data-confirm="<?= e(__('Create a new registration key for this customer? New TVs then need the new key.')) ?>">
              <?= Csrf::field() ?><input type="hidden" name="op" value="regen_key"><input type="hidden" name="id" value="<?= $hid ?>">
              <button class="btn btn-sm btn-outline-secondary"><i class="bi bi-arrow-repeat"></i> <?= e(__('New registration key')) ?></button></form>
          </div>
        </div>
        <div class="card"><div class="card-header d-flex align-items-center"><span><?= e(__('Invoices')) ?></span>
          <a class="ms-auto small" href="<?= e(admin_url('platform_invoices.php', ['hotel' => $hid])) ?>"><?= e(__('View all')) ?></a></div>
          <div class="table-responsive"><table class="table table-sm table-hc mb-0">
            <thead><tr><th><?= e(__('Number')) ?></th><th><?= e(__('Period')) ?></th><th class="text-end"><?= e(__('Total')) ?></th><th><?= e(__('Status')) ?></th></tr></thead>
            <tbody>
            <?php if (!$invoices): ?><tr><td colspan="4" class="text-muted text-center py-3"><?= e(__('No invoices yet.')) ?></td></tr><?php endif; ?>
            <?php foreach ($invoices as $inv): ?>
              <tr><td><a href="<?= e(admin_url('invoice.php', ['id' => $inv['id']])) ?>"><?= e($inv['number']) ?></a></td>
                <td class="small"><?= e(date('M Y', (int) strtotime($inv['period_from']))) ?></td>
                <td class="text-end"><?= e(money($inv['total'], $inv['currency'])) ?></td><td><?= Billing::statusBadge($inv) ?></td></tr>
            <?php endforeach; ?>
            </tbody></table></div>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="card mb-3"><div class="card-header"><?= e(__('Users')) ?></div>
          <ul class="list-group list-group-flush">
            <?php if (!$users): ?><li class="list-group-item text-muted"><?= e(__('No users yet.')) ?></li><?php endif; ?>
            <?php foreach ($users as $u): ?>
              <li class="list-group-item d-flex justify-content-between gap-2 small">
                <span><strong><?= e($u['full_name'] ?: $u['username']) ?></strong> · <?= e($u['username']) ?> · <?= e($u['email']) ?><?= (int) $u['is_active'] ? '' : ' · <span class="text-danger">' . e(__('Disabled')) . '</span>' ?></span>
                <span class="badge text-bg-light border"><?= e(role_label($u['role'])) ?></span>
              </li>
            <?php endforeach; ?>
          </ul>
        </div>
        <?php $hcChains = Chains::enabled() ? Chains::all() : []; if (Chains::enabled() && ($hcChains || $h['chain_id'])): ?>
        <div class="card mb-3"><div class="card-header"><i class="bi bi-diagram-3"></i> <?= e(__('Chain')) ?></div><div class="card-body">
          <form method="post" class="d-flex gap-2"><?= Csrf::field() ?><input type="hidden" name="op" value="set_chain"><input type="hidden" name="id" value="<?= $hid ?>">
            <select class="form-select" name="chain_id" aria-label="<?= e(__('Chain')) ?>"><option value="0"><?= e(__('— Not in a chain —')) ?></option>
              <?php foreach ($hcChains as $hcC): ?><option value="<?= (int) $hcC['id'] ?>"<?= (int) $h['chain_id'] === (int) $hcC['id'] ? ' selected' : '' ?>><?= e($hcC['name']) ?></option><?php endforeach; ?></select>
            <button class="btn btn-outline-primary"><?= e(__('Save')) ?></button></form>
        </div></div>
        <?php endif; ?>
        <div class="card"><div class="card-header"><?= e(__('Add a super admin')) ?></div><div class="card-body">
          <form method="post" class="row g-2" autocomplete="off">
            <?= Csrf::field() ?><input type="hidden" name="op" value="add_admin"><input type="hidden" name="id" value="<?= $hid ?>">
            <div class="col-sm-6"><input class="form-control" name="admin_username" placeholder="<?= e(__('Username')) ?>" required pattern="[A-Za-z0-9_.\-]{3,50}"></div>
            <div class="col-sm-6"><input class="form-control" name="admin_name" placeholder="<?= e(__('Full name')) ?>"></div>
            <div class="col-sm-6"><input class="form-control" type="email" name="admin_email" placeholder="<?= e(__('Email')) ?>" required></div>
            <div class="col-sm-6"><input class="form-control" type="password" name="admin_password" placeholder="<?= e(__('Password')) ?>" required autocomplete="new-password"></div>
            <div class="col-12"><button class="btn btn-outline-primary"><i class="bi bi-person-plus"></i> <?= e(__('Create super admin')) ?></button></div>
          </form>
        </div></div>
      </div>
    </div>
    <?php
    require __DIR__ . '/partials/footer.php';
    exit;
}

// ---------------------------------------------------------------- list
$q = req_str('q', $_GET, 60);
$fStatus = req_str('status', $_GET, 20);
$hotels = Hotels::all(null, $q, $fStatus);
$psUsers = PlatformScreens::usersPerCustomer(null); // 2.5 platform screens: "Users" column
$totals = ['hotels' => count($hotels), 'tvs' => array_sum(array_column($hotels, 'tv_count')), 'online' => array_sum(array_column($hotels, 'tv_online')),
    'suspended' => count(array_filter($hotels, fn ($h) => $h['status'] !== 'active'))];
$pageTitle = __('Customers');
require __DIR__ . '/partials/header.php';
?>
<div class="page-head">
  <div><h1><?= e(__('Customers')) ?></h1><p class="lead-sm"><?= e(__('Every customer on this platform, with its plan, TVs and status.')) ?></p></div>
  <a class="btn btn-primary" href="<?= e(admin_url('platform_hotels.php', ['action' => 'new'])) ?>"><i class="bi bi-plus-lg"></i> <?= e(__('New customer')) ?></a>
</div>
<div class="row g-3 mb-3">
  <?php foreach ([['bi-buildings', 'bg-soft-primary', __('Customers'), $totals['hotels']], ['bi-tv', 'bg-soft-info', __('TVs'), $totals['tvs']],
      ['bi-wifi', 'bg-soft-success', __('TVs online'), $totals['online']], ['bi-pause-circle', 'bg-soft-danger', __('Suspended / expired'), $totals['suspended']]] as [$icon, $cls, $label, $val]): ?>
    <div class="col-6 col-lg-3"><div class="card h-100"><div class="stat-card"><div class="stat-icon <?= e($cls) ?>"><i class="bi <?= e($icon) ?>"></i></div><div><div class="stat-value"><?= (int) $val ?></div><div class="stat-label"><?= e($label) ?></div></div></div></div></div>
  <?php endforeach; ?>
</div>
<?php require __DIR__ . '/partials/platform_screens_dashboard.php'; // 2.5: screens counters, top / offline customers ?>
<form class="d-flex flex-wrap gap-2 mb-3" method="get">
  <input class="form-control" style="max-width:18rem" name="q" value="<?= e($q) ?>" placeholder="<?= e(__('Search customer, city, email…')) ?>">
  <select class="form-select" style="max-width:12rem" name="status">
    <option value=""><?= e(__('All statuses')) ?></option>
    <?php foreach (['active' => __('Active'), 'suspended' => __('Suspended'), 'expired' => __('Expired')] as $s => $l): ?><option value="<?= e($s) ?>"<?= $fStatus === $s ? ' selected' : '' ?>><?= e($l) ?></option><?php endforeach; ?>
  </select>
  <button class="btn btn-outline-primary"><i class="bi bi-search"></i> <?= e(__('Filter')) ?></button>
</form>
<div class="card">
<?php if (!$hotels): ?>
  <div class="hc-empty"><i class="bi bi-buildings"></i><p class="mb-1"><strong><?= e(__('No customers found')) ?></strong></p></div>
<?php else: ?>
  <div class="table-responsive">
    <table class="table table-hc table-hover">
      <thead><tr><th><?= e(__('Customer')) ?></th><th class="d-none d-md-table-cell"><?= e(__('Plan')) ?></th><th><?= e(__('TVs')) ?></th><th class="d-none d-md-table-cell"><?= e(__('Screens (online/total)')) ?></th><th class="d-none d-md-table-cell"><?= e(__('Users')) ?></th><th class="d-none d-lg-table-cell"><?= e(__('Reseller')) ?></th><th><?= e(__('Status')) ?></th><th class="text-end"><?= e(__('Actions')) ?></th></tr></thead>
      <tbody>
      <?php foreach ($hotels as $h): $max = $h['max_tvs'] !== null ? (int) $h['max_tvs'] : ($h['plan_max_tvs'] !== null ? (int) $h['plan_max_tvs'] : null); ?>
        <tr>
          <td><a class="fw-semibold text-decoration-none" href="<?= e(admin_url('platform_hotels.php', ['action' => 'view', 'id' => $h['id']])) ?>"><?= e($h['name']) ?></a>
            <div class="small text-muted"><?= e(trim(($h['city'] ?? '') . ' #' . $h['id'])) ?><?= (int) $h['unpaid_invoices'] ? ' · <span class="text-danger">' . e(__(':n unpaid', ['n' => $h['unpaid_invoices']])) . '</span>' : '' ?></div></td>
          <td class="d-none d-md-table-cell small"><?= e($h['plan_name'] ?? '—') ?></td>
          <td class="text-nowrap"><?= e(tv_usage_label((int) $h['tv_count'], $max)) ?> <span class="small text-success">(<?= (int) $h['tv_online'] ?> <?= e(__('online')) ?>)</span></td>
          <td class="d-none d-md-table-cell text-nowrap"><a class="text-decoration-none" href="<?= e(admin_url('platform_customer.php', ['id' => $h['id'], 'tab' => 'screens'])) ?>"><span class="text-success"><?= (int) $h['tv_online'] ?></span> / <?= (int) $h['tv_count'] ?></a></td>
          <td class="d-none d-md-table-cell"><a class="text-decoration-none" href="<?= e(admin_url('platform_customer.php', ['id' => $h['id'], 'tab' => 'users'])) ?>"><?= (int) ($psUsers[(int) $h['id']] ?? 0) ?></a></td>
          <td class="d-none d-lg-table-cell small"><?= e($h['reseller_name'] ?? '—') ?></td>
          <td><?= Hotels::statusBadge($h['status'] === 'active' && $h['expires_at'] && strtotime((string) $h['expires_at']) < time() ? 'expired' : $h['status']) ?></td>
          <td class="text-end text-nowrap">
            <form method="post" class="d-inline"><?= Csrf::field() ?><input type="hidden" name="op" value="enter"><input type="hidden" name="id" value="<?= (int) $h['id'] ?>">
              <button class="btn btn-sm btn-primary" title="<?= e(__('Enter customer')) ?>"><i class="bi bi-box-arrow-in-right"></i> <span class="d-none d-sm-inline"><?= e(__('Enter')) ?></span></button></form>
            <a class="btn btn-sm btn-light border" href="<?= e(admin_url('platform_customer.php', ['id' => $h['id']])) ?>" title="<?= e(__('Customer details')) ?>"><i class="bi bi-card-list"></i></a>
            <a class="btn btn-sm btn-light border" href="<?= e(admin_url('platform_hotels.php', ['action' => 'edit', 'id' => $h['id']])) ?>" title="<?= e(__('Edit')) ?>"><i class="bi bi-pencil"></i></a>
          </td>
        </tr>
      <?php endforeach; ?>
      </tbody>
    </table>
  </div>
<?php endif; ?>
</div>
<?php require __DIR__ . '/partials/footer.php'; ?>
