<?php
declare(strict_types=1);

/**
 * Application configuration from config.php (generated by the installer, never
 * overwritten by the updater). Secrets live in .env and are read via Env.
 */
final class Config
{
    private static array $config = [];

    public static function load(string $file): void
    {
        if (is_file($file)) {
            $data = require $file;
            if (is_array($data)) {
                self::$config = $data;
            }
        }
    }

    public static function get(string $key, mixed $default = null): mixed
    {
        $node = self::$config;
        foreach (explode('.', $key) as $part) {
            if (!is_array($node) || !array_key_exists($part, $node)) {
                return $default;
            }
            $node = $node[$part];
        }
        return $node;
    }

    public static function set(string $key, mixed $value): void
    {
        self::$config[$key] = $value;
    }
}
