<?php
declare(strict_types=1);

/** Minimal .env loader (KEY=value, # comments, optional quotes). */
final class Env
{
    private static array $vars = [];

    public static function load(string $file): void
    {
        if (!is_file($file) || !is_readable($file)) {
            return;
        }
        foreach (file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [] as $line) {
            $line = trim($line);
            if ($line === '' || $line[0] === '#' || !str_contains($line, '=')) {
                continue;
            }
            [$key, $value] = explode('=', $line, 2);
            $key = trim($key);
            $value = trim($value);
            if (strlen($value) >= 2 && ($value[0] === '"' || $value[0] === "'") && $value[-1] === $value[0]) {
                $value = substr($value, 1, -1);
                $value = str_replace(['\\n', '\\"'], ["\n", '"'], $value);
            }
            self::$vars[$key] = $value;
        }
    }

    public static function get(string $key, mixed $default = null): mixed
    {
        if (array_key_exists($key, self::$vars)) {
            return self::$vars[$key];
        }
        $v = getenv($key);
        return $v === false ? $default : $v;
    }

    /** Serialise key/values into .env format. */
    public static function build(array $vars): string
    {
        $out = "# HotelCast secrets — generated by installer. NEVER commit or share this file.\n";
        foreach ($vars as $k => $v) {
            $v = (string) $v;
            $needsQuote = $v === '' || preg_match('/[\s#"\'=\\\\]/', $v);
            $out .= $k . '=' . ($needsQuote ? '"' . str_replace(['\\', '"', "\n"], ['\\\\', '\\"', '\\n'], $v) . '"' : $v) . "\n";
        }
        return $out;
    }
}
